import * as index from '@src/index'

test('index', () => {
  const expected = [
    'isChar', 'isntChar'
  , 'isCharPrimitive', 'isntCharPrimitive'
  , 'isCharObject', 'isntCharObject'

  , 'isIterable', 'isntIterable'
  , 'isAsyncIterable', 'isntAsyncIterable'

  , 'isNull', 'isntNull'
  , 'isUndefined', 'isntUndefined'

  , 'isString', 'isntString'
  , 'isStringPrimitive', 'isntStringPrimitive'
  , 'isStringObject', 'isntStringObject'

  , 'isNumber'

  , 'isObject', 'isntObject'

  , 'isPromise', 'isntPromise'
  , 'isPromiseLike', 'isntPromiseLike'

  , 'isFunction' , 'isntFunction'

  , 'isNodeJSWritableStream', 'isntNodeJSWritableStream'
  , 'isNodeJSReadableStream', 'isntNodeJSReadableStream'

  , 'isJson'
  , 'isntJson'

  , 'isJsonRpcNotification'
  , 'isJsonRpcRequest'
  , 'isJsonRpcSuccess'
  , 'isJsonRpcError'

  , 'isFalsy'
  , 'isntFalsy'

  , 'isHTMLAnchorElement'
  , 'isHTMLAppletElement'
  , 'isHTMLAreaElement'
  , 'isHTMLAudioElement'
  , 'isHTMLBaseElement'
  , 'isHTMLBaseFontElement'
  , 'isHTMLQuoteElement'
  , 'isHTMLBodyElement'
  , 'isHTMLBRElement'
  , 'isHTMLButtonElement'
  , 'isHTMLCanvasElement'
  , 'isHTMLTableCaptionElement'
  , 'isHTMLTableColElement'
  , 'isHTMLDataElement'
  , 'isHTMLDataListElement'
  , 'isHTMLModElement'
  , 'isHTMLDetailsElement'
  , 'isHTMLDialogElement'
  , 'isHTMLDirectoryElement'
  , 'isHTMLDivElement'
  , 'isHTMLDListElement'
  , 'isHTMLEmbedElement'
  , 'isHTMLFieldSetElement'
  , 'isHTMLFontElement'
  , 'isHTMLFormElement'
  , 'isHTMLFrameElement'
  , 'isHTMLFrameSetElement'
  , 'isHTMLHeadingElement'
  , 'isHTMLHeadElement'
  , 'isHTMLHRElement'
  , 'isHTMLHtmlElement'
  , 'isHTMLIFrameElement'
  , 'isHTMLImageElement'
  , 'isHTMLInputElement'
  , 'isHTMLLabelElement'
  , 'isHTMLLegendElement'
  , 'isHTMLLIElement'
  , 'isHTMLLinkElement'
  , 'isHTMLMapElement'
  , 'isHTMLMarqueeElement'
  , 'isHTMLMenuElement'
  , 'isHTMLMetaElement'
  , 'isHTMLMeterElement'
  , 'isHTMLObjectElement'
  , 'isHTMLOListElement'
  , 'isHTMLOptGroupElement'
  , 'isHTMLOptionElement'
  , 'isHTMLOutputElement'
  , 'isHTMLParagraphElement'
  , 'isHTMLParamElement'
  , 'isHTMLPictureElement'
  , 'isHTMLPreElement'
  , 'isHTMLProgressElement'
  , 'isHTMLScriptElement'
  , 'isHTMLSelectElement'
  , 'isHTMLSlotElement'
  , 'isHTMLSourceElement'
  , 'isHTMLSpanElement'
  , 'isHTMLStyleElement'
  , 'isHTMLTableElement'
  , 'isHTMLTableSectionElement'
  , 'isHTMLTableDataCellElement'
  , 'isHTMLTemplateElement'
  , 'isHTMLTextAreaElement'
  , 'isHTMLTableHeaderCellElement'
  , 'isHTMLTimeElement'
  , 'isHTMLTitleElement'
  , 'isHTMLTableRowElement'
  , 'isHTMLTrackElement'
  , 'isHTMLUListElement'
  , 'isHTMLVideoElement'
  ].sort()

  const result = Object.keys(index).sort()

  expect(result).toStrictEqual(expected)
})
